---
apiVersion: v1
kind: Service
metadata:
  name: rancher
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: rancher
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
